import React from 'react';
import ReactDOM from 'react-dom/client';
import { Provider } from 'react-redux';
import { RouterProvider } from 'react-router-dom';
import { store } from './redux/store';
import router from './router';
import AppBootstrap from './AppBootstrap';
import './styles/marketing.css';
import './styles/app.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><Provider store={store}><AppBootstrap><RouterProvider router={router} /></AppBootstrap></Provider></React.StrictMode>);
