const express = require('express');
const sessionRouter = require('./session');
const usersRouter = require('./users');
const productsRouter = require('./products');
const checkoutRouter = require('./checkout');
const accountRouter = require('./account');
const contactRouter = require('./contact');
const filesRouter = require('./files');
const trainerRouter = require('./trainer');
const router = express.Router();
const devRouter = require('./dev');
router.get('/health', (_req, res) => res.json({ status: 'ok', message: 'Sharp Fitness API is running' }));
router.use('/session', sessionRouter);
router.use('/users', usersRouter);
router.use('/products', productsRouter);
router.use('/checkout', checkoutRouter);
router.use('/account', accountRouter);
router.use('/contact', contactRouter);
router.use('/files', filesRouter);
router.use('/trainer', trainerRouter);
router.use('/dev', devRouter);
module.exports = router;
